### Get Applicant List
GET http://localhost:8080/api/v1/applicants

### Get Application List for Job Hunter
GET http://localhost:8080/api/v1/applications


### Get Application Details for Job Hunter
GET http://localhost:8080/api/v1/applications/{:id}
