name: CI/CD Pipeline Virtuosos Job Portal

# akan dijalankan ketika push ke branch main
on:
  push:
    branches:
      - main

# hal yang dijalankan
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Logging
        run: echo "Start deploy to production..."
      
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        run: |
          npm install -g pnpm@latest
          pnpm install
      
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd apps/final-assignment/backend
            git pull
            docker-compose build
            docker-compose down
            docker-compose up -d
